apiVersion: v1
kind: Secret
metadata:
  name: deepfake-api-secrets
  namespace: deepfake
type: Opaque
stringData:
  LOG_LEVEL: "INFO"
  MAX_UPLOAD_MB: "8"
  # MODEL_PATH: "checkpoints/unet_small_traced.pt"
