apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deepfake-detector-sm
  namespace: monitoring
  labels:
    release: mon
spec:
  selector:
    matchLabels:
      app: deepfake-detector
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
